### ISSUE TITLE
关于代理添加的问题

### ISSUE THREAD

**Issue by lzusa** [MMorinGlory/about_touhou_in_Bili#1]
想要具体了解一下如何正确的添加代理，我尝试了一下，代理数量大于2的时候，就会在运行一段时间后触发b站的反爬虫，由于我也并没有系统的学习过python，只是一个搞信息竞赛的，所以可能是操作上有一些问题，大大能否写一个添加proxy的具体方法和注意事项呢？感激不尽

**Comment by NaNillll** [comment]
非常抱歉，之前的代码添加代理的部分有问题（_因为我没有代理所以也没发现_）现在应该好了，你可以试一下

**Comment by lzusa** [comment]
谢谢大大

**Comment by NaNillll** [comment]
具体添加代理的方法，你可以上网搜索request库添加代理

**Comment by lzusa** [comment]
toolsT def is_thp 那里好像忘记更改了，代理已经用上了但是我稍微延长了sleep不然仍然会触发反爬虫。还是非常感谢作者

**Comment by lzusa** [comment]
好像依然存在一些问题，在跑了9000次之后还是被ban了，之前是跑1900次被ban

**Comment by NaNillll** [comment]
这个我也不是太清楚了，因为我也不是对这方面知识很熟悉
不过根据我的经验基本就是调整线程数，等待时间，随机化等待时间好像也有作用。另外b站不同时间好像反爬虫策略还不一样，应该是深夜会更严一点
